What is the shortcut to convert a Jupyter cell to markdown?

Here are the steps to follow:
1. Click on the code cell that you want to convert to a markdown cell.
2. Press the Esc key to enter command mode.
3. Press the M key to convert the cell to a markdown cell. (ไม่ต้อง m ใหญ่ แค่ m เล็กก็พอ)

In [4]:
import numpy as np
import pandas as pd

# Play with keyword-arguments

Also see section 3.2 (Funciton) in ch03.ipynb

In [3]:
# For completion of function keyword-arguments
def func_with_keywords(abra=1, abbra=2, abbbra=3):
    return abra, abbra, abbbra

In [3]:
func_with_keywords(abbbra=30)

(1, 2, 30)

In [4]:
func_with_keywords(abbra=200,10, 30)

SyntaxError: positional argument follows keyword argument (<ipython-input-4-a8cee65b9a2d>, line 1)

In [6]:
func_with_keywords(10, 30, abbra=200)

TypeError: func_with_keywords() got multiple values for argument 'abbra'

In [4]:
func_with_keywords(10, abbbra=30, abbra=200)

(10, 200, 30)

# Paste code from clipboard

In [7]:
%paste

UsageError: Line magic function `%paste` not found.


# Using magic

In [10]:
%whos

Variable             Type        Data/Info
------------------------------------------
func_with_keywords   function    <function func_with_keywo<...>ds at 0x0000023554FCF378>


In [11]:
foo = %pwd

In [12]:
print(foo)

C:\Users\Lenovo\Documents\Python\book\Python for Data Analysis\pydata-book


In [13]:
%pwd

'C:\\Users\\Lenovo\\Documents\\Python\\book\\Python for Data Analysis\\pydata-book'

In [47]:
'555\n555'

'555\n555'

In [49]:
'666\\n666'

'666\\n666'

In [40]:
print('555\n555')
print('666\\n666')

555
555
666\n666


In [53]:
print('555\n555'[2])
print('555\n555'[3])
print('555\n555'[4])

5


5


In [52]:
print('666\\n666'[2])
print('666\\n666'[3])
print('666\\n666'[4])

6
\
n


In [2]:
print('string')
'string'

string


'string'

# บท 4

## Basic Indexing and Slicing

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr
arr[5]
arr[5:8]

#As you can see, if you assign a scalar value to a slice, as in arr[5:8] = 12, the value is
#propagated (or broadcasted henceforth) to the entire selection.
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [5]:
l = list(range(10))
l[5:8] = [12]
l

[0, 1, 2, 3, 4, 12, 8, 9]

## Boolean Indexing 

In [6]:
a = 1; b = 2;
if (a == 1) & (b == 2):
    print('T & T')
if (a == 1) & (b == 0):
    print('T & F')
if (a == 0) & (b == 2):
    print('F & T')
if (a == 0) & (b == 0):
    print('F & F')

if (a == 1) | (b == 2):
    print('T | T')
if (a == 1) | (b == 0):
    print('T | F')
if (a == 0) | (b == 2):
    print('F | T')
if (a == 0) | (b == 0):
    print('F | F')

T & T
T | T
T | F
F | T


In [19]:
# ข้อควรระวังในการใช้ --> ต้องใส่วงเล็บ
if a == 9 & a == 1:
    print('F & T')
if  (a == 9) & (a == 1):
    print('(F) & (T)')

F & T


In [21]:
np.array([True, False]) | True

array([ True,  True])

In [22]:
np.array([True, False]) | False

array([ True, False])

In [23]:
np.logical_and(np.array([True, False]), False)

array([False, False])

## Array-Oriented Programming with Arrays

In [27]:
p = np.arange(0,1, 0.1)
print(p, len(p)) # ถ้า tick ไปถึง 1 len ก็จะเป็น 11

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9] 10


In [29]:
points = np.arange(-5, 5, 0.01)
points[-3:] # tick วิ่งไม่ถึง 5

array([4.97, 4.98, 4.99])

# บท 5

In [1]:
import pandas as pd
import numpy as np

## DataFrame

In [10]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four',
                             'five', 'six'])
frame2

,year,state,pop,debt
one,2000,Ohio,1.5,NaN
two,2001,Ohio,1.7,NaN
three,2002,Ohio,3.6,NaN
four,2001,Nevada,2.4,NaN
five,2002,Nevada,2.9,NaN
six,2003,Nevada,3.2,NaN


In [11]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

,year,state,pop,debt,eastern
one,2000,Ohio,1.5,NaN,True
two,2001,Ohio,1.7,NaN,True
three,2002,Ohio,3.6,NaN,True
four,2001,Nevada,2.4,NaN,False
five,2002,Nevada,2.9,NaN,False
six,2003,Nevada,3.2,NaN,False


จะทำให้ดีกว่าข้างบน โดยใช้ in ('Ohio',)

In [12]:
bool_series = frame2.state.map(lambda s: s in ('Ohio',))
bool_series

one       True
two       True
three     True
four     False
five     False
six      False
Name: state, dtype: bool

In [13]:
frame2['eastern_2'] = bool_series
frame2

,year,state,pop,debt,eastern,eastern_2
one,2000,Ohio,1.5,NaN,True,True
two,2001,Ohio,1.7,NaN,True,True
three,2002,Ohio,3.6,NaN,True,True
four,2001,Nevada,2.4,NaN,False,False
five,2002,Nevada,2.9,NaN,False,False
six,2003,Nevada,3.2,NaN,False,False


# บท 7

In [4]:
import pandas as pd
import numpy as np
from numpy import nan as NA

## Filtering Out Missing Data

In [5]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
                     [NA, NA, NA], [NA, 6.5, 3.]])
data[4] = NA

In [6]:
data

,0,1,2,4
0,1.0,6.5,3.0,NaN
1,1.0,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,NaN,6.5,3.0,NaN


In [7]:
data.dropna(axis=1, how='all')

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
2,NaN,NaN,NaN
3,NaN,6.5,3.0


จะ reimplement ให้เหมือน cell ข้างบนโดยใช้ numpy.all

In [33]:
data_arr = data.values
flag = pd.isnull(data).values
mask = ~flag.all(axis=0) # columns are retained

ans01 = data_arr[:, mask]
print(ans01)

ans02 = data.loc[:, mask]
ans02

[[1.  6.5 3. ]
 [1.  nan nan]
 [nan nan nan]
 [nan 6.5 3. ]]


,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
2,NaN,NaN,NaN
3,NaN,6.5,3.0


### Scratchpad

In [14]:
flag

array([[False, False, False,  True],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False, False,  True]])

In [18]:
flag.all(axis=0)

array([False, False, False,  True])

In [20]:
mask

array([ True,  True,  True, False])

จากที่ลองเล่นใน chap 05 "selecting data with a boolean array" จะเป็นการเลือก row
![](df_bool_sel_row.png)

In [24]:
print(data_arr)
print(data_arr[:, mask])

[[1.  6.5 3.  nan]
 [1.  nan nan nan]
 [nan nan nan nan]
 [nan 6.5 3.  nan]]
[[1.  6.5 3. ]
 [1.  nan nan]
 [nan nan nan]
 [nan 6.5 3. ]]


In [32]:
data.loc[:, mask]
data.iloc[:, mask]

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
2,NaN,NaN,NaN
3,NaN,6.5,3.0


## Filling In Missing Data

จะทำการ fill missing value ด้วย mean*100 เวลา data frame มีหลาย columns

In [76]:
np.random.seed(12345)

col1 = np.random.randn(10, 1)*0.5 + 5
col2 = np.random.randn(10, 1)*0.1 + 3
cols = np.hstack((col1, col2))
# cols[[4, 9]][:, [0, 1]] = np.nan # ถ้าใช้แบบนี้ original cols ไม่ถูก affected
cols[[4, 9]] = np.nan

data = pd.DataFrame(cols, columns=['X1', 'X2'])
mseries = data.apply(lambda x: x.mean(), axis=0)
mseries *= 100

data.fillna(mseries.to_dict())

,X1,X2
0,4.897646,3.100719
1,5.239472,2.870378
2,4.740281,3.027499
3,4.722135,3.022891
4,510.850932,300.496059
5,5.696703,3.088643
6,5.046454,2.799836
7,5.140873,2.962816
8,5.384511,3.166903
9,510.850932,300.496059


In [51]:
np.random.randn?

### Scratchpad

In [35]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result_vstack = np.vstack((arr1, arr2))
print("Vertical Stack:\n", result_vstack)

Vertical Stack:
 [[1 2 3]
 [4 5 6]]


In [37]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result_hstack = np.hstack((
                            arr1[:, np.newaxis], 
                            arr2[:, np.newaxis]
                         ))
print("Horizontal Stack:\n", result_hstack)

Horizontal Stack:
 [[1 4]
 [2 5]
 [3 6]]


In [71]:
cols

array([[4.89764617, 3.10071894],
       [5.23947167, 2.87037789],
       [4.74028064, 3.02749916],
       [4.72213485, 3.02289129],
       [       nan,        nan],
       [5.69670292, 3.08864293],
       [5.04645394, 2.79983627],
       [5.14087308, 2.96281575],
       [5.38451128, 3.16690253],
       [       nan,        nan]])

In [56]:
cols[[4, 9]][:, [0, 1]]

array([[5.98289029, 3.13529168],
       [5.62321737, 2.95614303]])

In [72]:
data

,X1,X2
0,4.897646,3.100719
1,5.239472,2.870378
2,4.740281,3.027499
3,4.722135,3.022891
4,NaN,NaN
5,5.696703,3.088643
6,5.046454,2.799836
7,5.140873,2.962816
8,5.384511,3.166903
9,NaN,NaN


In [75]:
mseries

X1    510.850932
X2    300.496059
dtype: float64

## Detecting and Filtering Outliers

Inspired by 
```
data[np.abs(data) > 3] = np.sign(data) * 3
data.describe()
```
จึงลองเขียน code ข้างล่างขึ้น

In [29]:
df = pd.DataFrame(np.arange(6).reshape((2, 3)))
print(df)
df[ df % 2 == 0] = df**2
print(df)

   0  1  2
0  0  1  2
1  3  4  5
   0   1  2
0  0   1  4
1  3  16  5


## Computing Indicator/Dummy Variables
จะทำการทดสอบ สิ่งที่อยากรู้ ต่อไปนี้

1. Python break จากลูปได้มั้ย
2. ทดสอบว่าทั้ง series เป็นจริง ด้วย all ได้หรือไม่
3. ถ้า access df.iloc[i, [0, 1, 2]] จะได้ DataFrame หรือ Series?
4. ทดสอบว่าสอง DataFrame เท่ากันทำยังไง

In [15]:
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('../datasets/movielens/movies.dat', sep='::',
                       header=None, names=mnames)
movies[:3]

C:\Users\Lenovo\miniconda3\envs\4book\lib\site-packages\pandas\io\parsers.py:767: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return read_csv(**locals())


,movie_id,title,genres
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance


In [16]:
all_genres = []
for x in movies.genres:
    all_genres.extend(x.split('|'))
genres = pd.unique(all_genres)
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [18]:
#scratchpad
np.where(genres == 'Comedy')

(array([2], dtype=int64),)

In [22]:
#scratchpad
a1 = np.array([2])
a2 = np.array([4, 8, 16])
a3 = np.array([32, 64])
a1

array([2])

In [23]:
#scratchpad
np.concatenate([a1, a2, a3])

array([ 2,  4,  8, 16, 32, 64])

In [17]:
#scratchpad
l = ['Comedy', 'Fantasy', 'Romance']
li = [np.where(genres == e)[0] for e in l] # np.where คืน result เป็น tuple of array เราต้องแกะออกมาหนึ่งชั้นให้เป็น array เฉยๆ
np.concatenate(li)

array([2, 4, 5], dtype=int64)

In [111]:
def findIndex(l):
    return np.concatenate([np.where(genres == e)[0] for e in l])

In [112]:
#scratchpad
findIndex('Comedy|Romance'.split('|'))

array([2, 5], dtype=int64)

### บททดสอบ 1

In [79]:
zero_matrix = np.zeros((len(movies), len(genres)))
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [116]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|')) # วิธีจากหนังสือ
    my_indices = findIndex(gen.split('|'))
    if i < 5:
        print(f"indices:{indices}\nmy_indices:{my_indices}")
    if not np.array_equal(indices, my_indices):
        print('Different indices found!')
        break

indices:[0 1 2]
my_indices:[0 1 2]
indices:[3 1 4]
my_indices:[3 1 4]
indices:[2 5]
my_indices:[2 5]
indices:[2 6]
my_indices:[2 6]
indices:[2]
my_indices:[2]


#### Scratchpad

In [24]:
ind=np.where([[False, False, True],[False, False, True]]) # เอา tuples ที่ return มา ทำ fancy indexing กันจะได้ ตำแหน่งที่เป็น True
ind

(array([0, 1], dtype=int64), array([2, 2], dtype=int64))

In [28]:
ar=np.arange(6).reshape(2, 3)
print(ar)
ar[ind[0], ind[1]] # fancy indexing

[[0 1 2]
 [3 4 5]]


array([2, 5])

In [108]:
dummies.columns.get_indexer('Comedy|Romance'.split('|'))

array([2, 5], dtype=int64)

### บททดสอบ 2

In [119]:
test = pd.Series([False]*len(movies.genres))

for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|')) # วิธีจากหนังสือ
    my_indices = findIndex(gen.split('|'))
    test[i] = np.array_equal(indices, my_indices)

In [134]:
test.all()

True

### บททดสอบ 3

In [127]:
movies.iloc[[2], 1:]

,title,genres
2,Grumpier Old Men (1995),Comedy|Romance


In [129]:
#mix #lower
movies.iloc[2, 1:]

title     Grumpier Old Men (1995)
genres             Comedy|Romance
Name: 2, dtype: object

### บททดสอบ 4

See https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.equals.html

# บท 8

## Database-Style DataFrame Joins

จะทำการทดสอบว่า การ join สองแบบได้ผลลัพธ์ตรงกัน โดยจะเอาผลลัพธ์มาต่อกันให้อยู่ใน data frame เดียวเพื่อให้ง่ายต่อการดู

In [30]:
left = pd.DataFrame({'key1': ['foo', 'foo', 'bar'],
                     'key2': ['one', 'two', 'one'],
                     'lval': [1, 2, 3]})
right = pd.DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],
                      'key2': ['one', 'one', 'one', 'two'],
                      'rval': [4, 5, 6, 7]})
m1 = pd.merge(left, right, on=['key1', 'key2'], how='outer')

In [31]:
left = pd.DataFrame({'lkey1': ['foo', 'foo', 'bar'],
                     'lkey2': ['one', 'two', 'one'],
                     'lval': [1, 2, 3]})
right = pd.DataFrame({'rkey1': ['foo', 'foo', 'bar', 'bar'],
                      'rkey2': ['one', 'one', 'one', 'two'],
                      'rval': [4, 5, 6, 7]})
m2 = pd.merge(left, right, left_on=['lkey1', 'lkey2'], right_on=['rkey1', 'rkey2'], how='outer')

In [55]:
lkey = m2.loc[:, ['lkey1','lkey2']]
rkey = m2.loc[:, ['rkey1','rkey2']]
keypart = np.where(lkey.isnull(), rkey, lkey)
valpart = m2[['lval','rval']]
m2_derived = pd.DataFrame(np.hstack((keypart, valpart)), columns=['key1', 'key2', 'lval', 'rval'])
m2_derived

,key1,key2,lval,rval
0,foo,one,1,4
1,foo,one,1,5
2,foo,two,2,NaN
3,bar,one,3,6
4,bar,two,NaN,7


In [56]:
m1.join(m2_derived.add_prefix('m2_'))

,key1,key2,lval,rval,m2_key1,m2_key2,m2_lval,m2_rval
0,foo,one,1.0,4.0,foo,one,1,4
1,foo,one,1.0,5.0,foo,one,1,5
2,foo,two,2.0,NaN,foo,two,2,NaN
3,bar,one,3.0,6.0,bar,one,3,6
4,bar,two,NaN,7.0,bar,two,NaN,7


### Scratchpad

In [33]:
m1

,key1,key2,lval,rval
0,foo,one,1.0,4.0
1,foo,one,1.0,5.0
2,foo,two,2.0,NaN
3,bar,one,3.0,6.0
4,bar,two,NaN,7.0


In [34]:
m2

,lkey1,lkey2,lval,rkey1,rkey2,rval
0,foo,one,1.0,foo,one,4.0
1,foo,one,1.0,foo,one,5.0
2,foo,two,2.0,NaN,NaN,NaN
3,bar,one,3.0,bar,one,6.0
4,NaN,NaN,NaN,bar,two,7.0


In [51]:
m2.loc[:, ['lkey1','lkey2']]

,lkey1,lkey2
0,foo,one
1,foo,one
2,foo,two
3,bar,one
4,NaN,NaN


In [44]:
np.hstack((np.where(lkey.isnull(), rkey, lkey), m2[['lval','rval']]))

array([['foo', 'one', 1.0, 4.0],
       ['foo', 'one', 1.0, 5.0],
       ['foo', 'two', 2.0, nan],
       ['bar', 'one', 3.0, 6.0],
       ['bar', 'two', nan, 7.0]], dtype=object)

In [57]:
m2[['lval','rval']] # ดูว่าเป็น float หรือ integer

,lval,rval
0,1.0,4.0
1,1.0,5.0
2,2.0,NaN
3,3.0,6.0
4,NaN,7.0


# 10.3.2

In [6]:
import pandas as pd
import numpy as np

In [56]:
#ลองเอง #มั่วๆ # อยากลองใช้ axis=1 ดูบ้่าง 

frame = pd.DataFrame({'data1': np.random.randn(5),
                      'data2': np.random.randn(5)})

grouped = frame[['data2']].groupby([1], axis=1)

key, group = next(iter(grouped)) 
group


,data2
0,0.214180
1,1.307079
2,1.782845
3,-0.238116
4,-0.527603


In [57]:
def get_stats_axis_1(group):
    return group.mean()

grouped = frame[['data2']].groupby([1], axis=1)

d_0 = grouped.min()
print(f"d_0=\n{d_0}")

d_1 = grouped.agg('min')
print(f"d_1=\n{d_1}")

d_0=
          1
0  0.214180
1  1.307079
2  1.782845
3 -0.238116
4 -0.527603
d_1=
          1
0  0.214180
1  1.307079
2  1.782845
3 -0.238116
4 -0.527603


In [58]:
d_2 = grouped.agg(lambda arr: arr.min())
print(f"d_2=\n{d_2}")

d_3 = grouped.agg(lambda arr: arr.min(axis=1))
print(f"d_3=\n{d_3}")

d_2=
    1
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN
d_3=
          1
0  0.214180
1  1.307079
2  1.782845
3 -0.238116
4 -0.527603


In [59]:
def named_func(arr):
    print(type(arr))
    return arr.min(axis=1)

d_4 = grouped.agg(named_func)
print(f"d_4=\n{d_4}")

<class 'pandas.core.frame.DataFrame'>
d_4=
          1
0  0.214180
1  1.307079
2  1.782845
3 -0.238116
4 -0.527603


In [62]:
frame2 = pd.DataFrame({'col': np.random.randn(5)})

d_5 = frame2.min(axis=1)
print(f"d_5=\n{d_5}")

d_6 = frame2.min() 
print(f"d_6=\n{d_6}")
# (single) column is retained and the column name becomes index in resulting series.
# ถ้าไม่เชื่อ ลองรัน pd.DataFrame({'a': np.arange(3), 'b': np.zeros(3)}).mean(axis=0)

d_5=
0   -0.107118
1   -1.092327
2    0.860038
3   -1.801309
4   -1.741511
dtype: float64
d_6=
col   -1.801309
dtype: float64


In [74]:
d_7 = grouped.agg(lambda arr: frame2.min(axis=1))
print(f"d_7=\n{d_7}")

d_8 = grouped.agg(lambda arr: frame2.min())
print(f"d_8=\n{d_8}")

type(frame2.min())

d_7=
          1
0 -0.107118
1 -1.092327
2  0.860038
3 -1.801309
4 -1.741511
d_8=
    1
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN


pandas.core.series.Series

In [75]:
d_9 = grouped.agg(lambda arr: pd.Series(np.arange(5)))
print(f"d_9=\n{d_9}")

d_10 = grouped.agg(lambda arr: pd.Series(np.arange(1)))
print(f"d_10=\n{d_10}")


d_9=
   1
0  0
1  1
2  2
3  3
4  4
d_10=
     1
0  0.0
1  NaN
2  NaN
3  NaN
4  NaN


In [123]:
#digression #return
# เพื่อยืนยันว่า สิ่งที่ต้อง return จาก function ที่ agg กิน เป็น row(column) ทั้งดุ้นไม่ใช่แค่ individual value
fme = pd.DataFrame({'key': ['a', 'a', 'b', 'b'], 'c1': [0, 5, 5, 10], 'c2': [0, 4, -1, -3]})
print(fme)
print(fme.groupby('key').agg('mean'))
fme.groupby('key').agg(lambda _: pd.Series({'c1': 20, 'c2': 25}))

  key  c1  c2
0   a   0   0
1   a   5   4
2   b   5  -1
3   b  10  -3
      c1   c2
key          
a    2.5  2.0
b    7.5 -2.0


,c1,c2
key,,
a,20,25
b,20,25


In [124]:
#digression ดูเหมือนว่าจะไม่จริง
# อาจจะเป็นเพราะว่าในส่วนนี้ ใช้การ groupby along axis=0 ดู 10.3.2 Revisited
fme.groupby('key').agg(lambda _: pd.Series({'555': 25}))

,c1,c2
key,,
a,25,25
b,25,25


In [76]:
d_11 = grouped.agg(lambda arr: pd.Series({'x': 1}))
print(f"d_11=\n{d_11}")

d_12 = grouped.agg(lambda arr: pd.Series({0: 1}))
print(f"d_12=\n{d_12}")

d_11=
    1
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN
d_12=
     1
0  1.0
1  NaN
2  NaN
3  NaN
4  NaN


In [79]:
def get_stats(group):
    return {'min': group.min(axis=0), 'max': group.max(),
            'count': group.count(), 'mean': group.mean()}
#grouped = frame.data2.groupby(quartiles) # โค้ดดั้งเดิมตามหนังสือ
#grouped = frame[['data2']].groupby([1], axis=1) # เอามาจากข้างบน
grouped.apply(get_stats)

1    {'min': [-0.5276032979508958], 'max': [1.78284...
dtype: object

# 10.3

#สงสัยคับ <br/>
ทำไม ของ tip dict มันอยู่ใน row เดียว แต่ของ quartiles dict มันกระจายออกไปหลายๆ row

In [92]:
tips = pd.read_csv('../examples/tips.csv')
# Add tip percentage of total bill
tips['tip_pct'] = tips['tip'] / tips['total_bill']
print(tips[:6])
#ลองเอง
tips.groupby('smoker').apply(lambda _: {'a': 555, 'b': 666})

   total_bill   tip smoker  day    time  size   tip_pct
0       16.99  1.01     No  Sun  Dinner     2  0.059447
1       10.34  1.66     No  Sun  Dinner     3  0.160542
2       21.01  3.50     No  Sun  Dinner     3  0.166587
3       23.68  3.31     No  Sun  Dinner     2  0.139780
4       24.59  3.61     No  Sun  Dinner     4  0.146808
5       25.29  4.71     No  Sun  Dinner     4  0.186240


smoker
No     {'a': 555, 'b': 666}
Yes    {'a': 555, 'b': 666}
dtype: object

In [82]:
frame = pd.DataFrame({'data1': np.random.randn(1000),
                      'data2': np.random.randn(1000)})
quartiles = pd.cut(frame.data1, 4)
quartiles[:10]

def get_stats(group):
    return {'min': group.min(), 'max': group.max(),
            'count': group.count(), 'mean': group.mean()}
grouped = frame.data2.groupby(quartiles)
grouped.apply(get_stats)

data1                  
(-3.147, -1.707]  min       -2.408887
                  max        2.089876
                  count     31.000000
                  mean      -0.136690
(-1.707, -0.272]  min       -3.144602
                  max        2.962203
                  count    335.000000
                  mean       0.011752
(-0.272, 1.163]   min       -3.104096
                  max        3.053262
                  count    505.000000
                  mean      -0.067428
(1.163, 2.597]    min       -2.268728
                  max        2.582556
                  count    129.000000
                  mean      -0.047113
Name: data2, dtype: float64

In [91]:
frame = pd.DataFrame({'data1': np.random.randn(1000),
                      'data2': np.random.randn(1000)})
quartiles = pd.cut(frame.data1, 4)
grouped = frame.data2.groupby(quartiles)
grouped.apply(lambda _: {'min': 555, 'max': 666,
            'count': 777, 'mean': 888})

data1                  
(-3.334, -1.685]  min      555
                  max      666
                  count    777
                  mean     888
(-1.685, -0.043]  min      555
                  max      666
                  count    777
                  mean     888
(-0.043, 1.599]   min      555
                  max      666
                  count    777
                  mean     888
(1.599, 3.241]    min      555
                  max      666
                  count    777
                  mean     888
Name: data2, dtype: int64

In [90]:
tip_qtiles = pd.cut(tips.tip_pct, 4)
tips.groupby(tip_qtiles).apply(lambda _: {'a': 555, 'b': 666})

tip_pct
(0.035, 0.204]    {'a': 555, 'b': 666}
(0.204, 0.373]    {'a': 555, 'b': 666}
(0.373, 0.542]    {'a': 555, 'b': 666}
(0.542, 0.71]     {'a': 555, 'b': 666}
dtype: object

In [100]:
# Cell นี้ กับ cell ถัดๆ(จนถึงที่มี variable grouped5)ไปคือคำตอบต่อข้อสงสัย #สงสัยคับ
frame2 = pd.DataFrame({'total_bill': tips['total_bill'],
                      'tip_pct': tips['tip_pct']})
frame2[:6]
quartiles2 = pd.cut(frame2.tip_pct, 4)
grouped2 = frame2.total_bill.groupby(quartiles2)
grouped2.apply(lambda _: {'min': 555, 'max': 666,
            'count': 777, 'mean': 888})


tip_pct              
(0.035, 0.204]  min      555
                max      666
                count    777
                mean     888
(0.204, 0.373]  min      555
                max      666
                count    777
                mean     888
(0.373, 0.542]  min      555
                max      666
                count    777
                mean     888
(0.542, 0.71]   min      555
                max      666
                count    777
                mean     888
Name: total_bill, dtype: int64

In [101]:
grouped3 = frame2['total_bill'].groupby(quartiles2)
grouped3.apply(lambda _: {'min': 555, 'max': 666,
            'count': 777, 'mean': 888})

tip_pct              
(0.035, 0.204]  min      555
                max      666
                count    777
                mean     888
(0.204, 0.373]  min      555
                max      666
                count    777
                mean     888
(0.373, 0.542]  min      555
                max      666
                count    777
                mean     888
(0.542, 0.71]   min      555
                max      666
                count    777
                mean     888
Name: total_bill, dtype: int64

In [102]:
grouped3 = frame2[['total_bill']].groupby(quartiles2)
grouped3.apply(lambda _: {'min': 555, 'max': 666,
            'count': 777, 'mean': 888})

tip_pct
(0.035, 0.204]    {'min': 555, 'max': 666, 'count': 777, 'mean':...
(0.204, 0.373]    {'min': 555, 'max': 666, 'count': 777, 'mean':...
(0.373, 0.542]    {'min': 555, 'max': 666, 'count': 777, 'mean':...
(0.542, 0.71]     {'min': 555, 'max': 666, 'count': 777, 'mean':...
dtype: object

In [103]:
grouped4 = frame2[['tip_pct', 'total_bill']].groupby(quartiles2)
grouped4.apply(lambda _: {'min': 555, 'max': 666,
            'count': 777, 'mean': 888})

tip_pct
(0.035, 0.204]    {'min': 555, 'max': 666, 'count': 777, 'mean':...
(0.204, 0.373]    {'min': 555, 'max': 666, 'count': 777, 'mean':...
(0.373, 0.542]    {'min': 555, 'max': 666, 'count': 777, 'mean':...
(0.542, 0.71]     {'min': 555, 'max': 666, 'count': 777, 'mean':...
dtype: object

In [105]:
grouped5 = frame2.groupby(quartiles2)
grouped5.apply(lambda _: {'min': 555, 'max': 666,
            'count': 777, 'mean': 888})

tip_pct
(0.035, 0.204]    {'min': 555, 'max': 666, 'count': 777, 'mean':...
(0.204, 0.373]    {'min': 555, 'max': 666, 'count': 777, 'mean':...
(0.373, 0.542]    {'min': 555, 'max': 666, 'count': 777, 'mean':...
(0.542, 0.71]     {'min': 555, 'max': 666, 'count': 777, 'mean':...
dtype: object

# 10.2

In [229]:
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
                   'data1' : [1, 90, 0, 0, 101],
                   'data2' : [0, 0, -1, 9, 0]}
                 )
df

,key1,data1,data2
0,a,1,0
1,a,90,0
2,b,0,-1
3,b,0,9
4,a,101,0


In [145]:
def peak_to_peak(arr):
    print(f"arr=\n{arr}", '\n')
    return arr.max() - arr.min()

grouped = df.groupby('key1')
grouped.agg(peak_to_peak)
# expect 
#   data1 data2
#a  100    0
#b    0   10

arr=
0      1
1     90
4    101
Name: data1, dtype: int64 

arr=
2    0
3    0
Name: data1, dtype: int64 

arr=
0    0
1    0
4    0
Name: data2, dtype: int64 

arr=
2   -1
3    9
Name: data2, dtype: int64 



,data1,data2
key1,,
a,100,0
b,0,10


In [232]:
def peak_to_peak(arr):
    print(arr.name)
    print(f"arr=\n{arr}", '\n')
    return arr.max() - arr.min()

grouped = df.groupby('key1')[['data1', 'data2']] # our function only works on numeric columns
grouped.apply(peak_to_peak)
# expect 
#   data1 data2
#a  100    0
#b    0   10

a
arr=
   data1  data2
0      1      0
1     90      0
4    101      0 

b
arr=
   data1  data2
2      0     -1
3      0      9 



,data1,data2
key1,,
a,100,0
b,0,10


# 10.3.2 Revisited
จากข้อมูลใน section นี้, section 10.3.2, และ 10.2 ได้ข้อสรุปว่า เวลาใช้ agg นั้น groupby axis=0,1 ทำงานไม่เหมือนกัน 
- ในกรณี 0 (grouping across row) aggregate function จะถูกเรียกซ้ำๆกันตามจำนวน column และ input ของมันจะเป็น slice ที่มาจาก แต่ละคอลัมน์
- ในกรณี 1 (grouping across column) aggregate function เวลาเรียกมันเอา input มาจาก ทุก row ในคราเดียว และมัน expect สิ่งที่ return เป็น vector ที่มี dimension เหมือน input

In [226]:
frame = pd.DataFrame({'data2': np.random.randn(5)})


grouped = frame.groupby(['a'], axis=1)

In [227]:
def min_wrp(arr):
    print(arr)
    print(type(arr))
    return arr.min()

grouped.agg(min_wrp)

      data2
0 -1.123093
1 -1.809533
2 -1.043320
3 -0.191002
4  1.224692
<class 'pandas.core.frame.DataFrame'>


,a
0,NaN
1,NaN
2,NaN
3,NaN
4,NaN


In [218]:
def min_axis(arr):
    return arr.min(axis=1)

grouped.agg(min_axis)

,a
0,0.162343
1,-0.079140
2,1.142868
3,-0.197265
4,-0.472589


In [219]:
df = pd.DataFrame([[1, 2, 4, 8, 16]])
df

,0,1,2,3,4
0,1,2,4,8,16


In [220]:
grouped = df.groupby(['a'])

In [221]:
def min_wrp(arr):
    print(arr)
    return arr.max()

grouped.agg(min_wrp)

0    1
Name: 0, dtype: int64
0    2
Name: 1, dtype: int64
0    4
Name: 2, dtype: int64
0    8
Name: 3, dtype: int64
0    16
Name: 4, dtype: int64


,0,1,2,3,4
a,1,2,4,8,16


# 10.3 Revisit

ใน section 10.3 ข้างบน เราได้เห็นว่า ถ้า เรา split a Series vs. a DataFrame เราได้ผลลัพธ์ต่างกัน
- Split a Series: ค่าใน dict ถูกแปลงเป็น หลายๆ row ใน Series ใหญ่
- Split a DataFrame: dict ยังคงเป็น dict และหนึ่ง dict ถูกเก็บไว้ใน 1 row ของ Series ใหญ่ with dtype: object
    - เข้าใจว่าเพราะคำตอบมี column เดียว ผลลัพธ์เลยเป็น Series ใหญ่ไม่ใช่ DataFrame

ใน Section revisit นี้ เราพบอีกข้อแตกต่างคื
- Split a Series: ไม่ว่า callable จะ return dict or Series จะได้ ผลลัพธ์เดียวกัน
- Split a DataFrame: ถ้า callable return Series มันจะกลายเป็น 1 row ของ DataFrame ใหญ่

In [13]:
?grouped_ser.apply

In [5]:
frame = pd.DataFrame({'data1': np.random.randn(1000),
                      'data2': np.random.randn(1000)})
quartiles = pd.cut(frame.data1, 4)

In [8]:
grouped_ser = frame['data2'].groupby(quartiles)
grouped_ser.apply(lambda _: {'min': 555, 'max': 666,
            'count': 777, 'mean': 888})

data1                  
(-2.916, -1.506]  min      555
                  max      666
                  count    777
                  mean     888
(-1.506, -0.101]  min      555
                  max      666
                  count    777
                  mean     888
(-0.101, 1.304]   min      555
                  max      666
                  count    777
                  mean     888
(1.304, 2.708]    min      555
                  max      666
                  count    777
                  mean     888
Name: data2, dtype: int64

In [9]:
grouped_ser.apply(lambda _: pd.Series({'min': 555, 'max': 666,
            'count': 777, 'mean': 888}))

data1                  
(-2.916, -1.506]  min      555
                  max      666
                  count    777
                  mean     888
(-1.506, -0.101]  min      555
                  max      666
                  count    777
                  mean     888
(-0.101, 1.304]   min      555
                  max      666
                  count    777
                  mean     888
(1.304, 2.708]    min      555
                  max      666
                  count    777
                  mean     888
Name: data2, dtype: int64

In [10]:
grouped_frame = frame[['data2']].groupby(quartiles)
grouped_frame.apply(lambda _: {'min': 555, 'max': 666,
            'count': 777, 'mean': 888})

data1
(-2.916, -1.506]    {'min': 555, 'max': 666, 'count': 777, 'mean':...
(-1.506, -0.101]    {'min': 555, 'max': 666, 'count': 777, 'mean':...
(-0.101, 1.304]     {'min': 555, 'max': 666, 'count': 777, 'mean':...
(1.304, 2.708]      {'min': 555, 'max': 666, 'count': 777, 'mean':...
dtype: object

In [11]:
grouped_frame.apply(lambda _: pd.Series({'min': 555, 'max': 666,
            'count': 777, 'mean': 888}))
# ถ้า เรา กำลัง split dataframe เมื่อ return Series จะกลายเป็น 1 row ใน Data Frame ใหญ่ (และไม่มี index 0)
# Behavior นี้ เหมือนใน #return_series_for_frame ใน chap10

,min,max,count,mean
data1,,,,
"(-2.916, -1.506]",555,666,777,888
"(-1.506, -0.101]",555,666,777,888
"(-0.101, 1.304]",555,666,777,888
"(1.304, 2.708]",555,666,777,888


![](return_series_for_frame.png)